package com.vrickey123.network

import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import com.vrickey123.model.api.MetObject
import com.vrickey123.model.api.MetSearchResult
import retrofit2.Response
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.GET
import retrofit2.http.Path
import retrofit2.http.Query

interface MetNetworkClient {

    companion object {
        /** Creates a MyNetworkClientImpl instance with auto-serialization handled by moshi
         * reflection [KotlinJsonAdapterFactory] and a under-the-hood networking implementation
         * generated by retrofit that uses OkHttpClient.
         * */
        fun create(): MetNetworkClient {
            val retrofit = Retrofit.Builder()
                .baseUrl("https://collectionapi.metmuseum.org")
                .addConverterFactory(MoshiConverterFactory.create(Serialization.moshi))
                .build()

            return retrofit.create(MetNetworkClient::class.java)
        }
    }

    @GET("/public/collection/v1/search")
    suspend fun search(
        @Query("q") query: String,
        @Query("hasImages") hasImages: Boolean,
        @Query("tags") tags: List<String>
    ): Response<MetSearchResult>

    @GET("public/collection/v1/objects/{objectID}")
    suspend fun getMetObject(@Path("objectID") objectID: Int): Response<MetObject>
}